### PR TITLE
README to AsciiDoc

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@aloubyansky yet another cosmetic change to see if the Travis CI hook works. Plz, do not merge yet.

**Comment by ppalaga** [comment]
@aloubyansky yes, looks like this PR has triggered a build! :) Let's wait for the result...

**Comment by ppalaga** [comment]
BTW, this is what the AsciiDoc formated README looks like when rendered by GitHub: https://github.com/ppalaga/pm/tree/160817-readme#provisioning-manager-tool

**Comment by ppalaga** [comment]
The ToC is missing. Let me fix it.

**Comment by ppalaga** [comment]
ToC is there now. 9cfb62e is ready to be merged from my PoV.

**Comment by aloubyansky** [comment]
Thanks, merged!

**Pull request merged**
